### PR TITLE
Update to Scala 2.12.0

### PR DESCRIPTION
**Pull request by keithschulze**
This updates to Scala 2.12.0. Script engine support has been refactored since the last scripting-scala release that was based on Scala 2.12.0-M4. See this commit:
https://github.com/scala/scala/commit/3cddeaa525fd6fe9860a27019fdf484297a8d3dd

We may want to hold off merging for a little bit because there are a couple of hacky things around ensuring the "java.class.path" property in System properties is up-to-date when ImageJ is launched using the imagej-launcher. Basically, the scala compiler uses the classpath specified in the System "java.class.path" property to resolve calls to other libraries. This works fine when testing or executing from Maven since Maven updates the "java.class.path" property. Unfortunately, the "java.class.path" property is not updated when ImageJ is launched using the imagej-launcher, so the scala script engine won't resolve any calls to ImageJ libraries. I plan to submit an issue and PR to imagej-launcher with a fix to update the "java.class.path" property, but I'm still trying to wrap my head around where best to do the update.

### CODE REVIEW

**Comment by ctrueden** [comment]
@keithschulze Thanks so much for working on this. I did notice that this plugin does not work correctly in an ImageJ installation, but did not have time to track down why. As things stand, the engine is non-functional before merging this PR, so, merging hardly makes the situation worse, does it?

I greatly appreciate your efforts in tracking down these issues and look forward to your follow-up PR. Let us know here if there is anything you need, questions you have, etc.

**Comment by keithschulze** [comment]
@ctrueden Thanks for looking at this. I agree that it doesn't make situation worse by merging this, which is why I decided to submit this PR anyway. Also thought it would help to explain what was missing in imagej-launcher. We can just remove the extra code once it's fixed in imagej-launcher.

**Comment by ctrueden** [comment]
> We can just remove the extra code once it's fixed in imagej-launcher.

Hmm, I am not sure we can "fix" that in the ImageJ launcher, if what you are asking for is to set the system class path to include all JAR files. Did you try launching ImageJ with the `--full-classpath` option? That option already behaves as such.

In the future, we plan to discontinue the current ImageJ Launcher in favor of a new one, which could address this requirement then. But that project is unfortunately quite a few items down on my [primary priority list](http://imagej.net/User:Rueden#Primary_projects).

**Comment by ctrueden** [comment]
One other thought: might it be possible to hack this component to dynamically add the requisite classpath elements, similar to how the Scala Jupyter kernel works? (See [here](https://github.com/4Quant/ImgLib2-Notebooks/blob/e7fec6d8d63dfe654413897de866a18fa1e8d674/Create%20Ops.ipynb) for an example...)

**Comment by keithschulze** [comment]
Hmmm, I think I may be missing something. I tried running an up-to-date copy of Fiji with the `--full-classpath` option i.e., 

> /Applications/Fiji.app/Contents/MacOS/ImageJ-macosx --full-classpath

but that doesn't seems to update the system classpath property. Running `Plugins>Utilities>ImageJ Properties` shows the following:
screen shot 2016-11-02 at 12 10 41 pm
I also tried the same from a newly packaged ImageJ using `mvn -Papp` from imagej master, and it gives the same result.

The idea I've been playing with in imagej-launcher is to update java.class.path property at the end of the ClassLauncher [launch method](https://github.com/imagej/imagej-launcher/blob/master/src/main/java/net/imagej/launcher/ClassLauncher.java#L242) using the ClassLoader parameter, similar to the way I did it in this PR. It seems to work. What are your thoughts about that approach? I will take a look at your alternative suggestion.

**Comment by ctrueden** [comment]
Unfortunately I am no expert; I suggest checking how [ammonium does it](https://github.com/alexarchambault/ammonium/blob/master/interpreter/api/src/main/scala/ammonite/api/Classpath.scala) (the library which backs the Scala Jupyter kernel). In any case, rather than hacking `java.class.path` I would suggest writing to a public scala channel asking what the best way of controlling dynamic class loading is. Surely there must be a better way?

**Comment by keithschulze** [comment]
There was indeed a better way. Looking more closely at the scala interpreter settings, there is an option to set the classpath directly... no hacking the `java.class.path`.

I squashed a couple of previous commits into the first one. Do you want me to squash it down to a single commit so that the history is cleaner? Thanks for your help.

**Comment by keithschulze** [comment]
@ctrueden Wondering if you've had a chance to review my last change, which avoids the need to adjust the `java.class.path`? I'd love to get this merged as I have some ImageJ plugins that depend on Scala 2.12.0. No rush though. Thanks in advance.

**Comment by ctrueden** [comment]
@keithschulze Sorry for the delay; I have been out with a serious injury. Back now!

I cleaned up the commits and pushed the result to master. (There was some undesirable style reformatting mixed in, which I removed.)

The result seems good to me, though I only tested very quickly. Could you please give it a try in a local ImageJ installation and see how it goes?

You can install it together with the Scala 2.12.0 libraries by doing:
```
mvn clean install -Dimagej.app.directory=/path/to/Fiji.app -Ddelete.other.versions=true
```

It would also be very nice to ship one or more script templates in the `script_templates` folder, similar to many of the other script languages. Would you mind concocting a quick Scala script example? Then the Script Editor will show Scala in the list of languages under Templates. Just the Greeting and/or Hello World Intro examples would be awesome to have. I did briefly try to make them already, but I suck at Scala and could not make them work immediately.

**Comment by keithschulze** [comment]
@ctrueden Sorry to hear about the injury, hope you are recovering well. Thanks a lot for this. 

> There was some undesirable style reformatting mixed in, which I removed.

Sorry about that. I haven't spent a lot of time getting vim to format Java code correctly, let alone for ImageJ. Is there a place I can find style recommendations for ImageJ dev.

> Could you please give it a try in a local ImageJ installation and see how it goes?

I tested it on my local installation and it seems to work correctly.

BTW, thanks for `mvn clean install -Dimagej.app.directory=/path/to/Fiji.app -Ddelete.other.versions=true`. I think I missed the `delete.other.versions` flag so I never managed to get it to run correctly i.e., the scala libraries were never updated.

>Would you mind concocting a quick Scala script example? 

Very happy to do a few examples. I'm a little low on bandwidth this week, but I will hopefully get some time toward the end of next week. Is there a repo with the existing `script_templates` for other langs that I can add to... I tried to search the repos but couldn't find anything obvious.

**Comment by ctrueden** [comment]
@keithschulze You're welcome! Thanks for pushing on it!

> Is there a place I can find style recommendations for ImageJ dev.

See the [Coding style](http://imagej.net/Coding_style) page, and in particular the [Eclipse code style profiles](http://imagej.net/Coding_style#Eclipse_code_style_profiles).

> I think I missed the `delete.other.versions` flag so I never managed to get it to run correctly i.e., the scala libraries were never updated.

Yeah, we really need to set that flag to true by default. And we also need `delete.older.versions` or similar, which is less aggressive about replacing JARs, only doing so when the dependency version of the current component is _newer_ than what's in the ImageJ installation. I will get around to adding that one of these days...

> Very happy to do a few examples. I'm a little low on bandwidth this week, but I will hopefully get some time toward the end of next week.

Awesome! And no worries, no rush.

> Is there a repo with the existing `script_templates` for other langs that I can add to...

What you want to do is add the examples to this `scripting-scala` repo. E.g.:
* `src/main/resources/script_templates/Intro/Greeting.scala`
* `src/main/resources/script_templates/Intro/Hello_World.scala`

See e.g. [those scripts in the `scripting-jython` repository](https://github.com/scijava/scripting-jython/tree/scripting-jython-0.4.0/src/main/resources/script_templates/Intro) for comparison. At a minimum, it would great to port those scripts over to Scala, and make sure they work elegantly as intended. (I have some doubts about that, since each script language is a little different and have various rough edges. In Scala's case: I'm not sure output values are able to be extracted from the script engine bindings afterwards.)

**Pull request closed without merging**
